### ISSUE TITLE
red LRM line covers blue bike lines

### ISSUE THREAD

**Issue by burritojustice** [mapzen-data/te-bike-lrm-mapzen#3]
The red LRM line often covers up the blue bike lanes. This makes it hard to tell if you’re actually on a bike lane or not. Maybe make it a dashed red line? Though per @nvkelso, we would probably have to restyle the dragging line...

**Comment by IndyHurt** [comment]
This could be done with a dashArray.  This is how I did it in my original map:

`lineOptions: {
        styles: [ {color: 'FFFFFF', opacity: 0.8, weight: 12},
          {color: '#2E6C97', opacity: 1, weight: 6, dashArray: '2,14'}
        ]},`

It could be added to index.js , possibly around line [298?](https://github.com/mapzen-data/te-bike-lrm-mapzen/blob/gh-pages/js/index.js#L298)

Here is where I have it implemented in my map:  [Dashed Line with LRM-Mapzen](https://github.com/IndyHurt/te-bike/blob/gh-pages/map/index.html#L37-L40)

**Comment by IndyHurt** [comment]
fixed with @hanbyul-here 's help!
see [pull request #4](https://github.com/mapzen-data/te-bike-lrm-mapzen/pull/4) merged this morning.
